//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBProjectt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Exam_Id { get; set; }
        public int Crs_Id { get; set; }
        public string Duration { get; set; }
        public int Mark { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
